builds:
  - id: kurt
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: -s -w
      -X kurt/internal/version.version={{.Version}}
      -X kurt/internal/version.gitSHA={{.Commit}}
      -X kurt/internal/version.buildTime={{.Date}}
      -extldflags "-static"