on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: actions/checkout@v2

      - run: go build ./cmd/kurt
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: actions/checkout@v2

      - run: go test ./cmd/kurt -v